# Generated by Django 5.1.15 on 2026-05-25 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'airport_lookup',
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='CityCodeLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=8, unique=True)),
                ('city_name', models.CharField(max_length=128)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'city_code_lookup',
            },
        ),
        migrations.CreateModel(
            name='MovementTypeMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(max_length=8, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('source_meaning', models.CharField(blank=True, max_length=255)),
                ('esg_relevance', models.CharField(choices=[('CONSUMPTION', 'Consumption'), ('PURCHASE', 'Purchase / receipt'), ('TRANSFER', 'Transfer'), ('REVERSAL', 'Reversal / return'), ('SCRAP', 'Scrapping / write-off'), ('ADJUSTMENT', 'Inventory adjustment'), ('UNKNOWN', 'Unknown')], max_length=32)),
                ('activity_interpretation', models.CharField(blank=True, max_length=64)),
                ('default_action', models.CharField(choices=[('COUNT_AS_CONSUMPTION', 'Count as consumption'), ('COUNT_AS_PURCHASE', 'Count as purchase'), ('FLAG_TRANSFER', 'Flag as transfer (exclude from emissions)'), ('FLAG_REVERSAL', 'Flag as reversal (link & net)'), ('IGNORE_NON_RELEVANT', 'Ignore (not ESG-relevant)'), ('NEEDS_ANALYST_REVIEW', 'Needs analyst review')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movement_type_mapping',
                'ordering': ['movement_type'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactorMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=64)),
                ('activity_subtype', models.CharField(blank=True, max_length=64)),
                ('method', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=16)),
                ('factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('factor_unit', models.CharField(default='kgCO2e', max_length=32)),
                ('source', models.CharField(default='DEFRA 2024 (illustrative)', max_length=128)),
                ('version', models.CharField(default='2024', max_length=32)),
                ('region', models.CharField(blank=True, default='global', max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emission_factor_mapping',
                'indexes': [models.Index(fields=['activity_type', 'activity_subtype'], name='emission_fa_activit_4e8a3b_idx')],
                'unique_together': {('activity_type', 'activity_subtype', 'method', 'unit', 'version', 'region')},
            },
        ),
        migrations.CreateModel(
            name='TravelCategoryMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_pattern', models.CharField(blank=True, max_length=128)),
                ('segment_type', models.CharField(max_length=32)),
                ('scope', models.IntegerField()),
                ('scope_category', models.CharField(max_length=64)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_categories', to='tenants.tenant')),
            ],
            options={
                'db_table': 'travel_category_mapping',
            },
        ),
        migrations.CreateModel(
            name='CostCenterLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_center_code', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('business_unit', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'cost_center_lookup',
                'unique_together': {('tenant', 'cost_center_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MaterialLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_code', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(blank=True, max_length=64)),
                ('default_unit', models.CharField(blank=True, max_length=16)),
                ('density_kg_per_l', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='tenants.tenant')),
            ],
            options={
                'db_table': 'material_lookup',
                'indexes': [models.Index(fields=['tenant', 'material_code'], name='material_lo_tenant__ff0d70_idx')],
                'unique_together': {('tenant', 'material_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MeterFacilityLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=128)),
                ('account_number', models.CharField(max_length=64)),
                ('meter_number', models.CharField(max_length=64)),
                ('service_address', models.CharField(blank=True, max_length=255)),
                ('facility_code', models.CharField(max_length=32)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_country', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='tenants.tenant')),
            ],
            options={
                'db_table': 'meter_facility_lookup',
                'indexes': [models.Index(fields=['tenant', 'meter_number'], name='meter_facil_tenant__e86026_idx')],
                'unique_together': {('tenant', 'provider', 'account_number', 'meter_number', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PlantLookup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_code', models.CharField(max_length=32)),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_country', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='tenants.tenant')),
            ],
            options={
                'db_table': 'plant_lookup',
                'indexes': [models.Index(fields=['tenant', 'plant_code'], name='plant_looku_tenant__8f1225_idx')],
                'unique_together': {('tenant', 'plant_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UnitMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_unit', models.CharField(max_length=16)),
                ('normalized_unit', models.CharField(max_length=16)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_mappings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'unit_mapping',
                'indexes': [models.Index(fields=['source_unit'], name='unit_mappin_source__ed24eb_idx')],
                'unique_together': {('tenant', 'source_unit', 'version')},
            },
        ),
    ]
