# Generated by Django 5.1.15 on 2026-05-25 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=32)),
                ('ingestion_method', models.CharField(choices=[('FILE_UPLOAD', 'File upload'), ('API_PULL', 'API pull')], max_length=32)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('api_sync_range_start', models.DateField(blank=True, null=True)),
                ('api_sync_range_end', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PROCESSING', max_length=16)),
                ('total_rows', models.IntegerField(default=0)),
                ('raw_rows_stored', models.IntegerField(default=0)),
                ('eligible_rows', models.IntegerField(default=0)),
                ('excluded_rows', models.IntegerField(default=0)),
                ('not_relevant_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('suspicious_rows', models.IntegerField(default=0)),
                ('low_confidence_rows', models.IntegerField(default=0)),
                ('llm_suggested_rows', models.IntegerField(default=0)),
                ('pending_rows', models.IntegerField(default=0)),
                ('approved_rows', models.IntegerField(default=0)),
                ('rejected_rows', models.IntegerField(default=0)),
                ('locked_rows', models.IntegerField(default=0)),
                ('plant_lookup_version', models.CharField(blank=True, max_length=32, null=True)),
                ('material_lookup_version', models.CharField(blank=True, max_length=32, null=True)),
                ('unit_mapping_version', models.CharField(blank=True, max_length=32, null=True)),
                ('meter_mapping_version', models.CharField(blank=True, max_length=32, null=True)),
                ('ef_version', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ingestion_batch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=32)),
                ('row_number', models.IntegerField()),
                ('raw_payload', models.JSONField()),
                ('parse_status', models.CharField(choices=[('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('EXCLUDED', 'Excluded')], default='PARSED', max_length=16)),
                ('eligibility_status', models.CharField(blank=True, max_length=32, null=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'raw_record',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['tenant', '-uploaded_at'], name='ingestion_b_tenant__c08af1_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['tenant', 'source_type'], name='ingestion_b_tenant__787894_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['batch', 'parse_status'], name='raw_record_batch_i_7a3258_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['batch', 'eligibility_status'], name='raw_record_batch_i_5df1ca_idx'),
        ),
    ]
