# Generated by Django 5.1.15 on 2026-05-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionbatch',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='duplicate_of_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_batches', to='ingestion.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='is_duplicate_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='sync_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='duplicate_of_raw_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_raw_rows', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='is_duplicate_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='row_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='source_event_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
