# Generated by Django 5.1.15 on 2026-05-25 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=32)),
                ('activity_type', models.CharField(max_length=64)),
                ('activity_subtype', models.CharField(blank=True, max_length=64, null=True)),
                ('scope', models.IntegerField(blank=True, null=True)),
                ('scope_category', models.CharField(blank=True, max_length=64, null=True)),
                ('eligibility_status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_RELEVANT', 'Not relevant'), ('NEEDS_REVIEW', 'Needs review'), ('FAILED', 'Failed'), ('EXCLUDED', 'Excluded')], max_length=32)),
                ('source_hierarchy_rank', models.IntegerField(blank=True, null=True)),
                ('source_of_truth', models.CharField(blank=True, max_length=64, null=True)),
                ('activity_basis', models.CharField(blank=True, max_length=64, null=True)),
                ('calculation_method', models.CharField(blank=True, max_length=64, null=True)),
                ('emission_method', models.CharField(blank=True, max_length=64, null=True)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('calendar_month', models.DateField(blank=True, null=True)),
                ('billing_days', models.IntegerField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=32, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_country', models.CharField(blank=True, max_length=64, null=True)),
                ('origin', models.CharField(blank=True, max_length=64, null=True)),
                ('destination', models.CharField(blank=True, max_length=64, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=16, null=True)),
                ('usage_per_day', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=64, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=128, null=True)),
                ('event_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('parent_event_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_reversal', models.BooleanField(default=False)),
                ('reversal_of', models.CharField(blank=True, max_length=128, null=True)),
                ('is_estimate', models.BooleanField(default=False)),
                ('estimate_reason', models.TextField(blank=True, null=True)),
                ('requires_reconciliation', models.BooleanField(default=False)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=128, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('data_quality_score', models.IntegerField(default=0)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('FAILED', 'Failed')], default='LOW', max_length=16)),
                ('method_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flags', models.JSONField(default=list)),
                ('field_provenance', models.JSONField(default=dict)),
                ('llm_suggestions', models.JSONField(default=list)),
                ('llm_suggestion_reviewed', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLARIFICATION_REQUESTED', 'Clarification requested'), ('MARKED_NOT_RELEVANT', 'Marked not relevant'), ('LOCKED', 'Locked')], default='PENDING', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.ingestionbatch')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tenants.tenant')),
            ],
            options={
                'db_table': 'normalized_activity',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('MARKED_NOT_RELEVANT', 'Marked not relevant'), ('CLARIFICATION_REQUESTED', 'Clarification requested'), ('LOCKED', 'Locked'), ('UNLOCK_REQUESTED', 'Unlock requested'), ('LLM_SUGGESTION_ACCEPTED', 'LLM suggestion accepted'), ('LLM_SUGGESTION_REJECTED', 'LLM suggestion rejected'), ('VALUE_OVERRIDDEN', 'Value overridden')], max_length=32)),
                ('comment', models.TextField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='activities.normalizedactivity')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'review_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_code', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='WARNING', max_length=8)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='activities.normalizedactivity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='tenants.tenant')),
            ],
            options={
                'db_table': 'validation_issue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroqSuggestionCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('missing_fields_hash', models.CharField(max_length=64)),
                ('response_json', models.JSONField()),
                ('model_used', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groq_cache', to='ingestion.rawrecord')),
            ],
            options={
                'db_table': 'groq_suggestion_cache',
                'unique_together': {('raw_record', 'missing_fields_hash')},
            },
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['tenant', 'review_status'], name='normalized__tenant__0c9331_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['tenant', 'source_type', 'eligibility_status'], name='normalized__tenant__c98eac_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['batch'], name='normalized__batch_i_8aa531_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['confidence_level'], name='normalized__confide_49946e_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedactivity',
            index=models.Index(fields=['activity_type', 'activity_date'], name='normalized__activit_4ee152_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['activity'], name='review_log_activit_a1bfda_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewlog',
            index=models.Index(fields=['action'], name='review_log_action_43a29f_idx'),
        ),
        migrations.AddIndex(
            model_name='validationissue',
            index=models.Index(fields=['activity', 'severity'], name='validation__activit_fde70b_idx'),
        ),
        migrations.AddIndex(
            model_name='validationissue',
            index=models.Index(fields=['issue_code'], name='validation__issue_c_b1eda5_idx'),
        ),
    ]
