# Generated by Django 5.1.15 on 2026-05-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedactivity',
            name='duplicate_of_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_activities', to='activities.normalizedactivity'),
        ),
        migrations.AddField(
            model_name='normalizedactivity',
            name='duplicate_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='action',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('MARKED_NOT_RELEVANT', 'Marked not relevant'), ('CLARIFICATION_REQUESTED', 'Clarification requested'), ('LOCKED', 'Locked'), ('UNLOCK_REQUESTED', 'Unlock requested'), ('LLM_SUGGESTION_ACCEPTED', 'LLM suggestion accepted'), ('LLM_SUGGESTION_REJECTED', 'LLM suggestion rejected'), ('VALUE_OVERRIDDEN', 'Value overridden'), ('MARKED_DUPLICATE', 'Marked duplicate'), ('MARKED_NOT_DUPLICATE', 'Marked not duplicate'), ('USE_AS_SOURCE_OF_TRUTH', 'Use as source of truth'), ('IGNORED_DUPLICATE', 'Ignored duplicate')], max_length=32),
        ),
    ]
