# Generated by Django 5.1.15 on 2026-05-25 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedTravelTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_payload', models.JSONField()),
                ('source_label', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploaded_travel_trip',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='uploaded_tr_uploade_84ba15_idx')],
            },
        ),
    ]
