"""Registry of validation flag codes and their default severity."""
from __future__ import annotations

# Severity: ERROR (data unusable as-is), WARNING (use with caution), INFO (provenance hint)
FLAG_SEVERITY: dict[str, str] = {
    # Generic
    "MISSING_REQUIRED_FIELD": "ERROR",
    "UNKNOWN_UNIT": "ERROR",
    "UNKNOWN_FACILITY": "WARNING",
    "NEGATIVE_VALUE": "WARNING",
    "ZERO_VALUE": "INFO",
    "DUPLICATE_REFERENCE": "WARNING",
    "DUPLICATE_FILE_UPLOAD": "WARNING",
    "DUPLICATE_ROW_IN_BATCH": "WARNING",
    "CROSS_BATCH_DUPLICATE": "WARNING",
    "DOUBLE_COUNT_RISK": "WARNING",
    "SUSPICIOUS_HIGH_VALUE": "WARNING",
    "LOW_CONFIDENCE": "INFO",
    "LLM_SUGGESTED_FIELD": "INFO",
    "LLM_SUGGESTION_FAILED": "WARNING",
    "MISSING_SOURCE_REFERENCE": "WARNING",
    "NOT_RELEVANT_ROW": "INFO",
    "NEEDS_ANALYST_REVIEW": "INFO",
    "REQUIRES_RECONCILIATION": "INFO",

    # SAP
    "UNKNOWN_PLANT_CODE": "WARNING",
    "UNKNOWN_MATERIAL_CODE": "WARNING",
    "UNKNOWN_MATERIAL_GROUP": "WARNING",
    "UNSUPPORTED_MOVEMENT_TYPE": "WARNING",
    "REVERSAL_ROW": "INFO",
    "RETURN_ROW": "INFO",
    "STOCK_TRANSFER_ROW": "INFO",
    "INVENTORY_ADJUSTMENT_ROW": "INFO",
    "NEGATIVE_QUANTITY": "WARNING",
    "ZERO_QUANTITY": "WARNING",
    "DUPLICATE_DOCUMENT": "WARNING",
    "DUPLICATE_SAP_ROW": "WARNING",
    "SUSPICIOUS_HIGH_QUANTITY": "WARNING",
    "MISSING_POSTING_DATE": "ERROR",
    "MISSING_QUANTITY": "ERROR",
    "MISSING_UNIT": "ERROR",
    "MISSING_FACILITY_MAPPING": "WARNING",
    "GERMAN_HEADER_MAPPING_USED": "INFO",
    "UNIT_DENSITY_CONVERSION_REQUIRED": "INFO",
    "PURCHASE_NOT_CONSUMPTION": "INFO",
    "DUPLICATE_FUEL_SOURCE": "WARNING",
    "SCRAP_REQUIRES_REVIEW": "INFO",

    # Utility
    "MISSING_METER_NUMBER": "WARNING",
    "MISSING_ACCOUNT_NUMBER": "WARNING",
    "MISSING_USAGE_KWH": "ERROR",
    "TOTAL_AMOUNT_ONLY": "WARNING",
    "AMOUNT_ONLY_NO_USAGE": "WARNING",
    "ZERO_KWH": "INFO",
    "NEGATIVE_KWH": "WARNING",
    "INVALID_BILLING_PERIOD": "ERROR",
    "BILLING_END_BEFORE_START": "ERROR",
    "BILLING_PERIOD_TOO_LONG": "WARNING",
    "BILLING_PERIOD_TOO_SHORT": "WARNING",
    "OVERLAPPING_BILLING_PERIOD": "WARNING",
    "DUPLICATE_BILL_ACCOUNT_PERIOD": "WARNING",
    "ESTIMATED_READING": "INFO",
    "MISSING_READING_TYPE": "WARNING",
    "POSSIBLE_AMENDED_BILL": "WARNING",
    "USAGE_SPIKE": "WARNING",
    "USAGE_SPIKE_AFTER_DAY_NORMALIZATION": "WARNING",
    "MISSING_TARIFF": "INFO",
    "DEMAND_MISSING_FOR_INDUSTRIAL_TARIFF": "INFO",
    "NON_CONSUMPTION_CHARGE": "INFO",
    "TAX_ONLY_ROW": "INFO",
    "LATE_FEE_ONLY_ROW": "INFO",
    "ADJUSTMENT_ROW": "INFO",
    "MULTIPLE_METER_SITE": "INFO",
    "MARKET_BASED_SCOPE2_EVIDENCE_MISSING": "WARNING",
    "GAS_UTILITY_DATA_DETECTED": "ERROR",

    # Travel
    "BOOKING_NOT_COMPLETED": "INFO",
    "CANCELLED_BOOKING": "INFO",
    "REFUNDED_BOOKING": "INFO",
    "VOIDED_BOOKING": "INFO",
    "DUPLICATE_TRAVEL_EVENT": "WARNING",
    "DUPLICATE_TRAVEL_SYNC": "WARNING",
    "UNKNOWN_TRAVEL_CATEGORY": "WARNING",
    "MISSING_FLIGHT_DISTANCE": "ERROR",
    "MISSING_ORIGIN_DESTINATION": "ERROR",
    "DISTANCE_ESTIMATED": "INFO",
    "RAIL_DISTANCE_ESTIMATED": "INFO",
    "CABIN_CLASS_MISSING": "WARNING",
    "UNKNOWN_CABIN_CLASS": "WARNING",
    "LAYOVER_SEGMENTS_MISSING": "WARNING",
    "ROUND_TRIP_AMBIGUITY": "WARNING",
    "ROUND_TRIP_DUPLICATE_RISK": "WARNING",
    "POSSIBLE_CODESHARE_DUPLICATE": "WARNING",
    "MISSING_HOTEL_NIGHTS": "WARNING",
    "MISSING_CHECKOUT": "ERROR",
    "ZERO_ROOM_NIGHTS": "WARNING",
    "HOTEL_NIGHTS_DATE_MISMATCH": "WARNING",
    "HOTEL_LOCATION_MISSING": "WARNING",
    "BOOKING_NOT_STAYED": "INFO",
    "ROOM_NIGHT_AMBIGUITY": "WARNING",
    "HOTEL_SPEND_INCLUDES_NON_ROOM_CHARGES": "WARNING",
    "BUNDLED_TRAVEL_PACKAGE": "WARNING",
    "COMMUTE_NOT_BUSINESS_TRAVEL": "INFO",
    "RENTAL_CAR_DOUBLE_COUNT_RISK": "WARNING",
    "GROUND_TRANSPORT_NO_ROUTING": "WARNING",
    "AMOUNT_ONLY_TRAVEL_ROW": "INFO",
    "PERSONAL_TRIP": "INFO",
    "SPEND_BASED_FALLBACK": "INFO",
}


def severity_for(code: str) -> str:
    return FLAG_SEVERITY.get(code, "WARNING")


# Friendly human descriptions for the dashboard tooltip.
FLAG_DESCRIPTION: dict[str, str] = {
    "UNKNOWN_PLANT_CODE": "SAP plant code not found in tenant lookup.",
    "UNKNOWN_MATERIAL_CODE": "SAP material code not found in tenant lookup.",
    "UNSUPPORTED_MOVEMENT_TYPE": "Movement type is not mapped — adapter cannot decide if this is consumption, purchase, or transfer.",
    "REVERSAL_ROW": "Movement type indicates a reversal — net against the original document.",
    "STOCK_TRANSFER_ROW": "Inventory transfer — not ESG-relevant.",
    "SUSPICIOUS_HIGH_QUANTITY": "Quantity unusually high vs typical activity for this material.",
    "MISSING_POSTING_DATE": "Posting date missing.",
    "MISSING_QUANTITY": "Quantity missing or unparseable.",
    "MISSING_FACILITY_MAPPING": "Plant or meter could not be resolved to a facility.",
    "GERMAN_HEADER_MAPPING_USED": "File header is in German; English mapping applied.",
    "PURCHASE_NOT_CONSUMPTION": "Goods receipt — fuel arrived but is not yet burned.",
    "DUPLICATE_DOCUMENT": "Document number already seen in this batch.",
    "DUPLICATE_FILE_UPLOAD": "This uploaded file appears to duplicate an earlier ingestion batch.",
    "DUPLICATE_ROW_IN_BATCH": "This raw source row appears more than once in the same batch.",
    "CROSS_BATCH_DUPLICATE": "This row or activity appears to duplicate an earlier batch.",
    "DOUBLE_COUNT_RISK": "This activity may count the same real-world event as another record.",
    "REQUIRES_RECONCILIATION": "An analyst must decide how this duplicate or correction should be treated.",
    "DUPLICATE_SAP_ROW": "This SAP movement row appears to duplicate an earlier SAP row.",
    "TOTAL_AMOUNT_ONLY": "Row has total amount but no usage — spend-based, low confidence.",
    "ESTIMATED_READING": "Utility reading marked estimated by provider.",
    "POSSIBLE_AMENDED_BILL": "An overlapping period exists; this may be an amended/correction bill.",
    "USAGE_SPIKE_AFTER_DAY_NORMALIZATION": "Daily usage rate significantly exceeds rolling baseline.",
    "GAS_UTILITY_DATA_DETECTED": "Row appears to be gas (therms/CCF/m3) — rejected from electricity import.",
    "CANCELLED_BOOKING": "Travel booking was cancelled.",
    "REFUNDED_BOOKING": "Travel booking was refunded.",
    "VOIDED_BOOKING": "Travel booking was voided.",
    "MISSING_FLIGHT_DISTANCE": "Flight has no distance and no airport codes to infer it.",
    "DISTANCE_ESTIMATED": "Distance estimated via great-circle from airport coordinates.",
    "UNKNOWN_CABIN_CLASS": "Cabin class code not recognized; defaulted to economy.",
    "POSSIBLE_CODESHARE_DUPLICATE": "Same flight time + airport pair already seen on another carrier ticket.",
    "DUPLICATE_TRAVEL_EVENT": "This travel segment appears to duplicate an earlier travel event.",
    "DUPLICATE_TRAVEL_SYNC": "This travel sync range was previously ingested.",
    "MISSING_CHECKOUT": "Hotel record has no check-out date — room-nights cannot be computed.",
    "ZERO_ROOM_NIGHTS": "Hotel check-in equals check-out.",
    "BUNDLED_TRAVEL_PACKAGE": "Flight+hotel bundled at a single amount — needs itemization.",
    "RENTAL_CAR_DOUBLE_COUNT_RISK": "Same city pickup/dropoff — risk of double-counting if employee fuel receipt also submitted.",
}
